name: Release

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    workflow_dispatch: # Manually on demand
    tags:
      - "v*"
    branches:
      - "*"
    schedule:
      # additionally run once per week (At 00:00 on Sunday) to maintain cache
      - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 8192
          base_image: raspios_lite:latest
          cpu: cortex-a7
          commands: |
            apt-get -y update
            apt-get -y install llvm-9 libgmp-dev libnuma-dev libncurses5
            wget -q http://downloads.haskell.org/%7Eghc/9.2.2/ghc-9.2.2-armv7-deb10-linux.tar.xz
            tar xf ghc-9.2.2-armv7-deb10-linux.tar.xz
            rm ghc-9.2.2-armv7-deb10-linux.tar.xz
            cd ghc-9.2.2/
            ./configure CONF_CC_OPTS_STAGE2="-marm -march=armv7-a" CFLAGS="-marm -march=armv7-a"
            make install
            ghc --version
