name: Release

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    workflow_dispatch: # Manually on demand
    tags:
      - "v*"
    branches:
      - "*"
    schedule:
      # additionally run once per week (At 00:00 on Sunday) to maintain cache
      - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 8192
          base_image: dietpi:rpi_armv8_bullseye
          commands: |
            apt update -y
            apt install -y software-properties-common
            add-apt-repository ppa:hvr/ghc
            apt update
            apt install -y ghc cabal-install
