name: Release

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    workflow_dispatch: # Manually on demand
    tags:
      - "v*"
    branches:
      - "*"
    schedule:
      # additionally run once per week (At 00:00 on Sunday) to maintain cache
      - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 8192
          base_image: raspios_lite_arm64:latest
          commands: |
            apt install -y libgmp-dev libnuma-dev libncurses5
            wget -q http://downloads.haskell.org/%7Eghc/9.0.1/ghc-9.0.1-aarch64-deb9-linux.tar.xz
            tar xf ghc-9.0.1-aarch64-deb9-linux.tar.xz
            rm ghc-9.0.1-aarch64-deb9-linux.tar.xz
            cd ghc-9.0.1/
            ./configure --prefix=/usr/local
            make install
            cd ..
            rm -rf ghc-9.0.1/
            ghc --version
            wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-aarch64-linux-gnu.tar.xz
            tar xf clang+llvm-14.0.6-aarch64-linux-gnu.tar.xz
            ls -la
            cd clang+llvm-14.0.6-aarch64-linux-gnu/
            cp -r * /usr/local/
            apt install git
            git clone https://github.com/haskell/cabal.git
            cd cabal/cabal-install/
            EXTRA_CONFIGURE_OPTS="" ./bootstrap.sh
